name: Hospital CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write
  checks: write
  id-token: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Permisos de ejecución
        run: chmod +x mvnw

      - name: Compilar y Empaquetar
        run: ./mvnw package --no-transfer-progress -DskipTests

      - name: Ejecutar Tests e Informe de Cobertura
        # 'verify' ejecuta unitarios, integración y genera el CSV de Jacoco
        run: ./mvnw verify --no-transfer-progress

      - name: Generar Informe de Resultados (UI)
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Reporte de Pruebas JUnit
          # Filtramos para evitar el error del summary.xml
          path: '**/target/*-reports/TEST-*.xml'
          reporter: java-junit

      - name: Generar Badge de Cobertura (Jacoco)
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: target/site/jacoco/jacoco.csv
          badges-directory: .github/badges

      - name: Commit y Push de los Badges
        if: github.event_name == 'push'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .github/badges/*.svg
          git commit -m "Update coverage badges" || exit 0
          git push

      - name: Subir Artifact JAR
        uses: actions/upload-artifact@v4
        with:
          name: hospital-jar
          path: target/*.jar
          retention-days: 1

  # Este job se ejecutará solo si el anterior (tests) termina con éxito
  deploy-simulation:
    needs: build-and-test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Info
        run: echo "Tests pasados. El artefacto está listo para Docker/K8s."